site_name: My Docs
site_url: https://sitename.example
repo_url: https://github.com/KamilBozz/mkdocs-material-tutorial.git
theme: 
  name: material
  font: 
    text: Merriweather Sans
    code: Red Hat Mono
  # icon: 
  #   logo: fontawesome/solid/k
  features:
    - navigation.footer
  palette: 
    # scheme: slate
    # primary: green
    # accent: deep purple

    # Dark Mode
      - scheme: slate
        toggle:
          icon: material/weather-sunny
          name: Dark mode
        primary: green
        accent: deep purple

    # Palette toggle for dark mode
      - scheme: default
        toggle:
          icon: material/weather-night
          name: Light mode
        primary: blue
        accent: deep orange

nav:
  - index.md
  - How to install: Set-1.md
  - Handling simple routes: Set-2.md
  - Different content types: Set-3.md
  - Set-4.md 
  - Troubleshooting.md
  - Glossary.md


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: 
      alternate_style: true
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.blocks.caption



# extra: 
#   social:
#     - icon: simple/linkedin

copyright: Copyright &copy; 2025 Kamil Bozkurt & Stefan Dorosh